# Generated by Django 4.2 on 2026-05-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('A', 'Accion'), ('H', 'Horror'), ('T', 'Thriller'), ('C', 'Comedia'), ('R', 'Romance'), ('F', 'Ciencia Ficcion')], max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('synopsis', models.TextField(max_length=200)),
            ],
        ),
    ]
